file_upload:
    path: /file/upload
    controller: App\ParserBundle\Presentation\Web\Controller\FileUploadController::index

file_upload_post:
    path: /file/upload/post
    controller: App\ParserBundle\Presentation\Web\Controller\FileUploadController::upload

app_login:
    path: /login
    controller:  App\ParserBundle\Presentation\Web\Controller\LoginController::login

app_logout:
    path: /logout
    methods: GET

rest_generate:
    path: /api/meme/generate
    methods: POST
    controller: App\ParserBundle\Presentation\Rest\Controller\MemeController::generateAction
